-- database m2_final_project
BEGIN TRANSACTION;

-- *************************************************************************************************
-- Drop all db objects in the proper order
-- *************************************************************************************************
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS entry, dictionary, collection CASCADE;

-- *************************************************************************************************
-- Create the tables and constraints
-- *************************************************************************************************

--users (name is pluralized because 'user' is a SQL keyword)
CREATE TABLE users (
	user_id SERIAL,
	username varchar(50) NOT NULL UNIQUE,
	password_hash varchar(200) NOT NULL,
	role varchar(50) NOT NULL,
	CONSTRAINT PK_user PRIMARY KEY (user_id)
);

CREATE TABLE collection (
	id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE dictionary (
	id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
	collection_id int REFERENCES collection(id) ON DELETE CASCADE
);

CREATE TABLE entry (
	id SERIAL PRIMARY KEY,
    word VARCHAR NOT NULL,
	pos VARCHAR(50),
	definition VARCHAR NOT NULL,
	dictionary_id int REFERENCES dictionary(id) ON DELETE CASCADE NOT NULL
);

-- *************************************************************************************************
-- Insert some sample starting data
-- *************************************************************************************************

-- Users
-- Password for all users is password
INSERT INTO
    users (username, password_hash, role)
VALUES
    ('user', '$2a$10$tmxuYYg1f5T0eXsTPlq/V.DJUKmRHyFbJ.o.liI1T35TFbjs2xiem','ROLE_USER'),
    ('admin','$2a$10$tmxuYYg1f5T0eXsTPlq/V.DJUKmRHyFbJ.o.liI1T35TFbjs2xiem','ROLE_ADMIN');



insert into collection(name) values ('Tom''s Dictionary Collection');
insert into collection(name) values ('Foreign Language Dictionaries');

insert into dictionary(name, collection_id) values ('Dictionary of Some A Words', 1);
insert into dictionary(name, collection_id) values ('English to French', 2);
insert into dictionary(name, collection_id) values ('English to Spanish', 2);
insert into dictionary(name, collection_id) values ('Disc Golf Terms', 1);
insert into dictionary(name, collection_id) values ('Gardening Terms', 1);

insert into entry (word, pos, definition, dictionary_id) values ('Aard-vark', 'n.', 'An edentate mammal, of the genus Orycteropus, somewhat resembling a pig, common in some parts of Southern Africa. It burrows in the ground, and feeds entirely on ants, which it catches with its long, slimy tongue.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aard-wolf', 'n.', 'A carnivorous quadruped (Proteles Lalandii), of South Africa, resembling the fox and hyena. See Proteles.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aaronic', 'a.', 'Alt. of Aaronical', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aaronical', 'a.', 'Pertaining to Aaron, the first high priest of the Jews.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aaron''s rod', null, 'A rod with one serpent twined around it, thus differing from the caduceus of Mercury, which has two.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aaron''s rod', null, 'A plant with a tall flowering stem; esp. the great mullein, or hag-taper, and the golden-rod.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ab-', null, 'A prefix in many words of Latin origin. It signifies from, away , separating, or departure, as in abduct, abstract, abscond. See A-(6).', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ab', 'n.', 'The fifth month of the Jewish year according to the ecclesiastical reckoning, the eleventh by the civil computation, coinciding nearly with August.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaca', 'n.', 'The Manila-hemp plant (Musa textilis); also, its fiber. See Manila hemp under Manila.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abacinate', 'v. t.', 'To blind by a red-hot metal plate held before the eyes.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abacination', 'n.', 'The act of abacinating.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaciscus', 'n.', 'One of the tiles or squares of a tessellated pavement; an abaculus.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abacist', 'n.', 'One who uses an abacus in casting accounts; a calculator.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aback', 'adv.', 'Toward the back or rear; backward.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aback', 'adv.', 'Behind; in the rear.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aback', 'adv.', 'Backward against the mast; -- said of the sails when pressed by the wind.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aback', 'n.', 'An abacus.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abactinal', 'a.', 'Pertaining to the surface or end opposite to the mouth in a radiate animal; -- opposed to actinal.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaction', 'n.', 'Stealing cattle on a large scale.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abactor', 'n.', 'One who steals and drives away cattle or beasts by herds or droves.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaculi', 'pl. ', 'of Abaculus', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaculus', 'n.', 'A small tile of glass, marble, or other substance, of various colors, used in making ornamental patterns in mosaic pavements.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abacuses', 'pl. ', 'of Abacus', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaci', 'pl. ', 'of Abacus', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abacus', 'n.', 'A table or tray strewn with sand, anciently used for drawing, calculating, etc.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abacus', 'n.', 'A calculating table or frame; an instrument for performing arithmetical calculations by balls sliding on wires, or counters in grooves, the lowest line representing units, the second line, tens, etc. It is still employed in China.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abacus', 'n.', 'The uppermost member or division of the capital of a column, immediately under the architrave. See Column.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abacus', 'n.', 'A tablet, panel, or compartment in ornamented or mosaic work.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abacus', 'n.', 'A board, tray, or table, divided into perforated compartments, for holding cups, bottles, or the like; a kind of cupboard, buffet, or sideboard.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abada', 'n.', 'The rhinoceros.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaddon', 'n.', 'The destroyer, or angel of the bottomless pit; -- the same as Apollyon and Asmodeus.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaddon', 'n.', 'Hell; the bottomless pit.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaft', 'prep.', 'Behind; toward the stern from; as, abaft the wheelhouse.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaft', 'adv.', 'Toward the stern; aft; as, to go abaft.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaisance', 'n.', 'Obeisance.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaiser', 'n.', 'Ivory black or animal charcoal.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaist', 'p. p.', 'Abashed; confounded; discomfited.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abalienate', 'v. t.', 'To transfer the title of from one to another; to alienate.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abalienate', 'v. t.', 'To estrange; to withdraw.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abalienate', 'v. t.', 'To cause alienation of (mind).', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abalienation', 'n.', 'The act of abalienating; alienation; estrangement.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abalone', 'n.', 'A univalve mollusk of the genus Haliotis. The shell is lined with mother-of-pearl, and used for ornamental purposes; the sea-ear. Several large species are found on the coast of California, clinging closely to the rocks.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aband', 'v. t.', 'To abandon.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aband', 'v. t.', 'To banish; to expel.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandoned', 'imp. & p. p.', 'of Abandon', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandoning', 'p. pr. & vb. n.', 'of Abandon', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandon', 'v. t.', 'To cast or drive out; to banish; to expel; to reject.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandon', 'v. t.', 'To give up absolutely; to forsake entirely ; to renounce utterly; to relinquish all connection with or concern on; to desert, as a person to whom one owes allegiance or fidelity; to quit; to surrender.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandon', 'v. t.', 'Reflexively: To give (one''s self) up without attempt at self-control; to yield (one''s self) unrestrainedly; -- often in a bad sense.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandon', 'v. t.', 'To relinquish all claim to; -- used when an insured person gives up to underwriters all claim to the property covered by a policy, which may remain after loss or damage by a peril insured against.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandon', 'v.', 'Abandonment; relinquishment.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandon', 'n.', 'A complete giving up to natural impulses; freedom from artificial constraint; careless freedom or ease.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandoned', 'a.', 'Forsaken, deserted.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandoned', 'a.', 'Self-abandoned, or given up to vice; extremely wicked, or sinning without restraint; irreclaimably wicked ; as, an abandoned villain.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandonedly', 'adv.', 'Unrestrainedly.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandonee', 'n.', 'One to whom anything is legally abandoned.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandoner', 'n.', 'One who abandons.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandonment', 'n.', 'The act of abandoning, or the state of being abandoned; total desertion; relinquishment.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandonment', 'n.', 'The relinquishment by the insured to the underwriters of what may remain of the property insured after a loss or damage by a peril insured against.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandonment', 'n.', 'The relinquishment of a right, claim, or privilege, as to mill site, etc.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandonment', 'n.', 'The voluntary leaving of a person to whom one is bound by a special relation, as a wife, husband, or child; desertion.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandonment', 'n.', 'Careless freedom or ease; abandon.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abandum', 'n.', 'Anything forfeited or confiscated.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abanet', 'n.', 'See Abnet.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abanga', 'n.', 'A West Indian palm; also the fruit of this palm, the seeds of which are used as a remedy for diseases of the chest.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abannation', 'n.', 'Alt. of Abannition', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abannition', 'n.', 'Banishment.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abarticulation', 'n.', 'Articulation, usually that kind of articulation which admits of free motion in the joint; diarthrosis.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abased', 'imp. & p. p.', 'of Abase', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abasing', 'p. pr. & vb. n.', 'of Abase', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abase', 'a.', 'To lower or depress; to throw or cast down; as, to abase the eye.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abase', 'a.', 'To cast down or reduce low or lower, as in rank, office, condition in life, or estimation of worthiness; to depress; to humble; to degrade.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abased', 'a.', 'Lowered; humbled.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abased', 'a.', 'Borne lower than usual, as a fess; also, having the ends of the wings turned downward towards the point of the shield.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abasedly', 'adv.', 'Abjectly; downcastly.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abasement', 'n.', 'The act of abasing, humbling, or bringing low; the state of being abased or humbled; humiliation.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaser', 'n.', 'He who, or that which, abases.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abashed', 'imp. & p. p.', 'of Abash', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abashing', 'p. pr. & vb. n.', 'of Abash', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abash', 'v. t.', 'To destroy the self-possession of; to confuse or confound, as by exciting suddenly a consciousness of guilt, mistake, or inferiority; to put to shame; to disconcert; to discomfit.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abashedly', 'adv.', 'In an abashed manner.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abashment', 'n.', 'The state of being abashed; confusion from shame.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abassi', 'n.', 'Alt. of Abassis', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abassis', 'n.', 'A silver coin of Persia, worth about twenty cents.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abatable', 'a.', 'Capable of being abated; as, an abatable writ or nuisance.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abated', 'imp. & p. p.', 'of Abate', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abating', 'p. pr. & vb. n.', 'of Abate', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abate', 'v. t.', 'To beat down; to overthrow.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abate', 'v. t.', 'To bring down or reduce from a higher to a lower state, number, or degree; to lessen; to diminish; to contract; to moderate; to cut short; as, to abate a demand; to abate pride, zeal, hope.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abate', 'v. t.', 'To deduct; to omit; as, to abate something from a price.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abate', 'v. t.', 'To blunt.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abate', 'v. t.', 'To reduce in estimation; to deprive.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abate', 'v. t.', 'To bring entirely down or put an end to; to do away with; as, to abate a nuisance, to abate a writ.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abate', 'v. t.', 'To diminish; to reduce. Legacies are liable to be abated entirely or in proportion, upon a deficiency of assets.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abate', 'v. t.', 'To decrease, or become less in strength or violence; as, pain abates, a storm abates.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abate', 'v. t.', 'To be defeated, or come to naught; to fall through; to fail; as, a writ abates.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abate', 'n.', 'Abatement.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abatement', 'n.', 'The act of abating, or the state of being abated; a lessening, diminution, or reduction; removal or putting an end to; as, the abatement of a nuisance is the suppression thereof.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abatement', 'n.', 'The amount abated; that which is taken away by way of reduction; deduction; decrease; a rebate or discount allowed.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abatement', 'n.', 'A mark of dishonor on an escutcheon.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abatement', 'n.', 'The entry of a stranger, without right, into a freehold after the death of the last possessor, before the heir or devisee.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abater', 'n.', 'One who, or that which, abates.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abatis', 'n.', 'Alt. of Abattis', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abattis', 'n.', 'A means of defense formed by felled trees, the ends of whose branches are sharpened and directed outwards, or against the enemy.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abatised', 'a.', 'Provided with an abatis.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abator', 'n.', 'One who abates a nuisance.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abator', 'n.', 'A person who, without right, enters into a freehold on the death of the last possessor, before the heir or devisee.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abattoirs', 'pl. ', 'of Abattoir', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abattoir', 'n.', 'A public slaughterhouse for cattle, sheep, etc.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abature', 'n.', 'Grass and sprigs beaten or trampled down by a stag passing through them.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abatvoix', 'n.', 'The sounding-board over a pulpit or rostrum.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abawed', 'p. p.', 'Astonished; abashed.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaxial', 'a.', 'Alt. of Abaxile', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abaxile', 'a.', 'Away from the axis or central line; eccentric.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abay', 'n.', 'Barking; baying of dogs upon their prey. See Bay.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abb', 'n.', 'Among weavers, yarn for the warp. Hence, abb wool is wool for the abb.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abba', 'n.', 'Father; religious superior; -- in the Syriac, Coptic, and Ethiopic churches, a title given to the bishops, and by the bishops to the patriarch.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbacies', 'pl. ', 'of Abbacy', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbacy', 'n.', 'The dignity, estate, or jurisdiction of an abbot.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbatial', 'a.', 'Belonging to an abbey; as, abbatial rights.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbatical', 'a.', 'Abbatial.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbe', 'n.', 'The French word answering to the English abbot, the head of an abbey; but commonly a title of respect given in France to every one vested with the ecclesiastical habit or dress.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbess', 'n.', 'A female superior or governess of a nunnery, or convent of nuns, having the same authority over the nuns which the abbots have over the monks. See Abbey.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbeys', 'pl. ', 'of Abbey', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbey', 'n.', 'A monastery or society of persons of either sex, secluded from the world and devoted to religion and celibacy; also, the monastic building or buildings.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbey', 'n.', 'The church of a monastery.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbot', 'n.', 'The superior or head of an abbey.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbot', 'n.', 'One of a class of bishops whose sees were formerly abbeys.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbotship', 'n.', 'The state or office of an abbot.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviated', 'imp. & p. p.', 'of Abbreviate', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviating', 'p. pr. & vb. n.', 'of Abbreviate', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviate', 'v. t.', 'To make briefer; to shorten; to abridge; to reduce by contraction or omission, especially of words written or spoken.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviate', 'v. t.', 'To reduce to lower terms, as a fraction.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviate', 'a.', 'Abbreviated; abridged; shortened.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviate', 'a.', 'Having one part relatively shorter than another or than the ordinary type.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviate', 'n.', 'An abridgment.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviated', 'a.', 'Shortened; relatively short; abbreviate.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviation', 'n.', 'The act of shortening, or reducing.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviation', 'n.', 'The result of abbreviating; an abridgment.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviation', 'n.', 'The form to which a word or phrase is reduced by contraction and omission; a letter or letters, standing for a word or phrase of which they are a part; as, Gen. for Genesis; U.S.A. for United States of America.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviation', 'n.', 'One dash, or more, through the stem of a note, dividing it respectively into quavers, semiquavers, or demi-semiquavers.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviator', 'n.', 'One who abbreviates or shortens.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviator', 'n.', 'One of a college of seventy-two officers of the papal court whose duty is to make a short minute of a decision on a petition, or reply of the pope to a letter, and afterwards expand the minute into official form.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviatory', 'a.', 'Serving or tending to abbreviate; shortening; abridging.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviature', 'n.', 'An abbreviation; an abbreviated state or form.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abbreviature', 'n.', 'An abridgment; a compendium or abstract.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abb wool', null, 'See Abb.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('A B C', null, 'The first three letters of the alphabet, used for the whole alphabet.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('A B C', null, 'A primer for teaching the alphabet and first elements of reading.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('A B C', null, 'The simplest rudiments of any subject; as, the A B C of finance.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdal', 'n.', 'A religious devotee or dervish in Persia.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abderian', 'a.', 'Given to laughter; inclined to foolish or incessant merriment.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abderite', 'n.', 'An inhabitant of Abdera, in Thrace.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdest', 'n.', 'Purification by washing the hands before prayer; -- a Mohammedan rite.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicable', 'a.', 'Capable of being abdicated.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicant', 'a.', 'Abdicating; renouncing; -- followed by of.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicant', 'n.', 'One who abdicates.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicated', 'imp. & p. p.', 'of Abdicate', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicating', 'p. pr. & vb. n.', 'of Abdicate', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicate', 'v. t.', 'To surrender or relinquish, as sovereign power; to withdraw definitely from filling or exercising, as a high office, station, dignity; as, to abdicate the throne, the crown, the papacy.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicate', 'v. t.', 'To renounce; to relinquish; -- said of authority, a trust, duty, right, etc.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicate', 'v. t.', 'To reject; to cast off.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicate', 'v. t.', 'To disclaim and expel from the family, as a father his child; to disown; to disinherit.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicate', 'v. i.', 'To relinquish or renounce a throne, or other high office or dignity.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdication', 'n.', 'The act of abdicating; the renunciation of a high office, dignity, or trust, by its holder; commonly the voluntary renunciation of sovereign power; as, abdication of the throne, government, power, authority.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicative', 'a.', 'Causing, or implying, abdication.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdicator', 'n.', 'One who abdicates.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abditive', 'a.', 'Having the quality of hiding.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abditory', 'n.', 'A place for hiding or preserving articles of value.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdomen', 'n.', 'The belly, or that part of the body between the thorax and the pelvis. Also, the cavity of the belly, which is lined by the peritoneum, and contains the stomach, bowels, and other viscera. In man, often restricted to the part between the diaphragm and the commencement of the pelvis, the remainder being called the pelvic cavity.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdomen', 'n.', 'The posterior section of the body, behind the thorax, in insects, crustaceans, and other Arthropoda.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdominal', 'a.', 'Of or pertaining to the abdomen; ventral; as, the abdominal regions, muscles, cavity.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdominal', 'a.', 'Having abdominal fins; belonging to the Abdominales; as, abdominal fishes.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdominals', 'pl. ', 'of Abdominal', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdominales', 'pl. ', 'of Abdominal', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdominal', 'n.', 'A fish of the group Abdominales.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdominales', 'n. pl.', 'A group including the greater part of fresh-water fishes, and many marine ones, having the ventral fins under the abdomen behind the pectorals.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdominalia', 'n. pl.', 'A group of cirripeds having abdominal appendages.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdominoscopy', 'n.', 'Examination of the abdomen to detect abdominal disease.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdominothoracic', 'a.', 'Relating to the abdomen and the thorax, or chest.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abdominous', 'a.', 'Having a protuberant belly; pot-bellied.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abduced', 'imp. & p. p.', 'of Abduce', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abducing', 'p. pr. & vb. n.', 'of Abduce', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abduce', 'v. t.', 'To draw or conduct away; to withdraw; to draw to a different part.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abducted', 'imp. & p. p.', 'of Abduct', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abducting', 'p. pr. & vb. n.', 'of Abduct', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abduct', 'v. t.', 'To take away surreptitiously by force; to carry away (a human being) wrongfully and usually by violence; to kidnap.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abduct', 'v. t.', 'To draw away, as a limb or other part, from its ordinary position.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abduction', 'n.', 'The act of abducing or abducting; a drawing apart; a carrying away.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abduction', 'n.', 'The movement which separates a limb or other part from the axis, or middle line, of the body.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abduction', 'n.', 'The wrongful, and usually the forcible, carrying off of a human being; as, the abduction of a child, the abduction of an heiress.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abduction', 'n.', 'A syllogism or form of argument in which the major is evident, but the minor is only probable.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abductor', 'n.', 'One who abducts.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abductor', 'n.', 'A muscle which serves to draw a part out, or form the median line of the body; as, the abductor oculi, which draws the eye outward.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abeam', 'adv.', 'On the beam, that is, on a line which forms a right angle with the ship''s keel; opposite to the center of the ship''s side.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abear', 'v. t.', 'To bear; to behave.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abear', 'v. t.', 'To put up with; to endure.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abearance', 'n.', 'Behavior.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abearing', 'n.', 'Behavior.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abecedarian', 'n.', 'One who is learning the alphabet; hence, a tyro.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abecedarian', 'n.', 'One engaged in teaching the alphabet.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abecedarian', 'a.', 'Alt. of Abecedary', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abecedary', 'a.', 'Pertaining to, or formed by, the letters of the alphabet; alphabetic; hence, rudimentary.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abecedary', 'n.', 'A primer; the first principle or rudiment of anything.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abed', 'adv.', 'In bed, or on the bed.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abed', 'adv.', 'To childbed (in the phrase "brought abed," that is, delivered of a child).', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abegge', null, 'Same as Aby.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abele', 'n.', 'The white poplar (Populus alba).', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abelian', 'n.', 'Alt. of Abelonian', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abelite', 'n.', 'Alt. of Abelonian', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abelonian', 'n.', 'One of a sect in Africa (4th century), mentioned by St. Augustine, who states that they married, but lived in continence, after the manner, as they pretended, of Abel.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abelmosk', 'n.', 'An evergreen shrub (Hibiscus -- formerly Abelmoschus -- moschatus), of the East and West Indies and Northern Africa, whose musky seeds are used in perfumery and to flavor coffee; -- sometimes called musk mallow.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aber-de-vine', 'n.', 'The European siskin (Carduelis spinus), a small green and yellow finch, related to the goldfinch.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberr', 'v. i.', 'To wander; to stray.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberrance', 'n.', 'Alt. of Aberrancy', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberrancy', 'n.', 'State of being aberrant; a wandering from the right way; deviation from truth, rectitude, etc.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberrant', 'a.', 'Wandering; straying from the right way.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberrant', 'a.', 'Deviating from the ordinary or natural type; exceptional; abnormal.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberrate', 'v. i.', 'To go astray; to diverge.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberration', 'n.', 'The act of wandering; deviation, especially from truth or moral rectitude, from the natural state, or from a type.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberration', 'n.', 'A partial alienation of reason.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberration', 'n.', 'A small periodical change of position in the stars and other heavenly bodies, due to the combined effect of the motion of light and the motion of the observer; called annual aberration, when the observer''s motion is that of the earth in its orbit, and daily or diurnal aberration, when of the earth on its axis; amounting when greatest, in the former case, to 20.4'''', and in the latter, to 0.3''''. Planetary aberration is that due to the motion of light and the motion of the planet relative to the earth.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberration', 'n.', 'The convergence to different foci, by a lens or mirror, of rays of light emanating from one and the same point, or the deviation of such rays from a single focus; called spherical aberration, when due to the spherical form of the lens or mirror, such form giving different foci for central and marginal rays; and chromatic aberration, when due to different refrangibilities of the colored rays of the spectrum, those of each color having a distinct focus.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberration', 'n.', 'The passage of blood or other fluid into parts not appropriate for it.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberration', 'n.', 'The producing of an unintended effect by the glancing of an instrument, as when a shot intended for A glances and strikes B.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberrational', 'a.', 'Characterized by aberration.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberuncate', 'v. t.', 'To weed out.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Aberuncator', 'n.', 'A weeding machine.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abetted', 'imp. & p. p.', 'of Abet', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abetting', 'p. pr. & vb. n.', 'of Abet', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abet', 'v. t.', 'To instigate or encourage by aid or countenance; -- used in a bad sense of persons and acts; as, to abet an ill-doer; to abet one in his wicked courses; to abet vice; to abet an insurrection.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abet', 'v. t.', 'To support, uphold, or aid; to maintain; -- in a good sense.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abet', 'v. t.', 'To contribute, as an assistant or instigator, to the commission of an offense.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abet', 'n.', 'Act of abetting; aid.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abetment', 'n.', 'The act of abetting; as, an abetment of treason, crime, etc.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abettal', 'n.', 'Abetment.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abetter', 'n.', 'Alt. of Abettor', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abettor', 'n.', 'One who abets; an instigator of an offense or an offender.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abevacuation', 'n.', 'A partial evacuation.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abeyance', 'n.', 'Expectancy; condition of being undetermined.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abeyance', 'n.', 'Suspension; temporary suppression.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abeyancy', 'n.', 'Abeyance.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abeyant', 'a.', 'Being in a state of abeyance.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhal', 'n.', 'The berries of a species of cypress in the East Indies.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhominable', 'a.', 'Abominable.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhominal', 'a.', 'Inhuman.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorred', 'imp. & p. p.', 'of Abhor', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorring', 'p. pr. & vb. n.', 'of Abhor', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhor', 'v. t.', 'To shrink back with shuddering from; to regard with horror or detestation; to feel excessive repugnance toward; to detest to extremity; to loathe.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhor', 'v. t.', 'To fill with horror or disgust.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhor', 'v. t.', 'To protest against; to reject solemnly.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhor', 'v. i.', 'To shrink back with horror, disgust, or dislike; to be contrary or averse; -- with', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorrence', 'n.', 'Extreme hatred or detestation; the feeling of utter dislike.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorrency', 'n.', 'Abhorrence.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorrent', 'a.', 'Abhorring; detesting; having or showing abhorrence; loathing; hence, strongly opposed to; as, abhorrent thoughts.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorrent', 'a.', 'Contrary or repugnant; discordant; inconsistent; -- followed by to.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorrent', 'a.', 'Detestable.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorrently', 'adv.', 'With abhorrence.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorrer', 'n.', 'One who abhors.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorrible', 'a.', 'Detestable.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorring', 'n.', 'Detestation.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abhorring', 'n.', 'Object of abhorrence.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abib', 'n.', 'The first month of the Jewish ecclesiastical year, corresponding nearly to our April. After the Babylonish captivity this month was called Nisan.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abidance', 'n.', 'The state of abiding; abode; continuance; compliance (with).', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abode', 'imp. & p. p.', 'of Abide', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abid', null, 'of Abide', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abiding', 'p. pr. & vb. n.', 'of Abide', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abide', 'v. i.', 'To wait; to pause; to delay.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abide', 'v. i.', 'To stay; to continue in a place; to have one''s abode; to dwell; to sojourn; -- with with before a person, and commonly with at or in before a place.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abide', 'v. i.', 'To remain stable or fixed in some state or condition; to continue; to remain.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abide', 'v. t.', 'To wait for; to be prepared for; to await; to watch for; as, I abide my time.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abide', 'v. t.', 'To endure; to sustain; to submit to.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abide', 'v. t.', 'To bear patiently; to tolerate; to put up with.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abide', 'v. t.', 'To stand the consequences of; to answer for; to suffer for.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abider', 'n.', 'One who abides, or continues.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abider', 'n.', 'One who dwells; a resident.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abiding', 'a.', 'Continuing; lasting.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abidingly', 'adv.', 'Permanently.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abies', 'n.', 'A genus of coniferous trees, properly called Fir, as the balsam fir and the silver fir. The spruces are sometimes also referred to this genus.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abietene', 'n.', 'A volatile oil distilled from the resin or balsam of the nut pine (Pinus sabiniana) of California.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abietic', 'a.', 'Of or pertaining to the fir tree or its products; as, abietic acid, called also sylvic acid.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abietin', 'n.', 'Alt. of Abietine', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abietine', 'n.', 'A resinous obtained from Strasburg turpentine or Canada balsam. It is without taste or smell, is insoluble in water, but soluble in alcohol (especially at the boiling point), in strong acetic acid, and in ether.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abietinic', 'a.', 'Of or pertaining to abietin; as, abietinic acid.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abietite', 'n.', 'A substance resembling mannite, found in the needles of the common silver fir of Europe (Abies pectinata).', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abigail', 'n.', 'A lady''s waiting-maid.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abiliment', 'n.', 'Habiliment.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abilities', 'pl. ', 'of Ability', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ability', 'n.', 'The quality or state of being able; power to perform, whether physical, moral, intellectual, conventional, or legal; capacity; skill or competence in doing; sufficiency of strength, skill, resources, etc.; -- in the plural, faculty, talent.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abime', 'n.', 'Alt. of Abyme', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abyme', 'n.', 'A abyss.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abiogenesis', 'n.', 'The supposed origination of living organisms from lifeless matter; such genesis as does not involve the action of living parents; spontaneous generation; -- called also abiogeny, and opposed to biogenesis.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abiogenetic', 'a.', 'Of or pertaining to abiogenesis.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abiogenist', 'n.', 'One who believes that life can be produced independently of antecedent.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abiogenous', 'a.', 'Produced by spontaneous generation.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abiogeny', 'n.', 'Same as Abiogenesis.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abiological', 'a.', 'Pertaining to the study of inanimate things.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abirritant', 'n.', 'A medicine that diminishes irritation.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abirritate', 'v. t.', 'To diminish the sensibility of; to debilitate.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abirritation', 'n.', 'A pathological condition opposite to that of irritation; debility; want of strength; asthenia.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abirritative', 'a.', 'Characterized by abirritation or debility.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abit', null, '3d sing. pres. of Abide.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abject', 'a.', 'Cast down; low-lying.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abject', 'a.', 'Sunk to a law condition; down in spirit or hope; degraded; servile; groveling; despicable; as, abject posture, fortune, thoughts.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abject', 'a.', 'To cast off or down; hence, to abase; to degrade; to lower; to debase.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abject', 'n.', 'A person in the lowest and most despicable condition; a castaway.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjectedness', 'n.', 'A very abject or low condition; abjectness.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjection', 'n.', 'The act of bringing down or humbling.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjection', 'n.', 'The state of being rejected or cast out.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjection', 'n.', 'A low or downcast state; meanness of spirit; abasement; degradation.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjectly', 'adv.', 'Meanly; servilely.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjectness', 'n.', 'The state of being abject; abasement; meanness; servility.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjudge', 'v. t.', 'To take away by judicial decision.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjudicate', 'v. t.', 'To reject by judicial sentence; also, to abjudge.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjudication', 'n.', 'Rejection by judicial sentence.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjugate', 'v. t.', 'To unyoke.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjunctive', 'a.', 'Exceptional.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjuration', 'n.', 'The act of abjuring or forswearing; a renunciation upon oath; as, abjuration of the realm, a sworn banishment, an oath taken to leave the country and never to return.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjuration', 'n.', 'A solemn recantation or renunciation; as, an abjuration of heresy.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjuratory', 'a.', 'Containing abjuration.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjured', 'imp. & p. p.', 'of Abjure', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjuring', 'p. pr. & vb. n.', 'of Abjure', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjure', 'v. t.', 'To renounce upon oath; to forswear; to disavow; as, to abjure allegiance to a prince. To abjure the realm, is to swear to abandon it forever.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjure', 'v. t.', 'To renounce or reject with solemnity; to recant; to abandon forever; to reject; repudiate; as, to abjure errors.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjure', 'v. i.', 'To renounce on oath.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjurement', 'n.', 'Renunciation.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Abjurer', 'n.', 'One who abjures.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablactate', 'v. t.', 'To wean.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablactation', 'n.', 'The weaning of a child from the breast, or of young beasts from their dam.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablactation', 'n.', 'The process of grafting now called inarching, or grafting by approach.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablaqueate', 'v. t.', 'To lay bare, as the roots of a tree.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablaqueation', 'n.', 'The act or process of laying bare the roots of trees to expose them to the air and water.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablastemic', 'a.', 'Non-germinal.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablation', 'n.', 'A carrying or taking away; removal.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablation', 'n.', 'Extirpation.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablation', 'n.', 'Wearing away; superficial waste.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablatitious', 'a.', 'Diminishing; as, an ablatitious force.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablative', 'a.', 'Taking away or removing.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablative', 'a.', 'Applied to one of the cases of the noun in Latin and some other languages, -- the fundamental meaning of the case being removal, separation, or taking away.', 1);
insert into entry (word, pos, definition, dictionary_id) values ('Ablative', null, 'The ablative case.', 1);

insert into entry (word, pos, definition, dictionary_id) values ('apple', 'n.', 'pomme', 2);
insert into entry (word, pos, definition, dictionary_id) values ('book', 'n.', 'livre', 2);
insert into entry (word, pos, definition, dictionary_id) values ('car', 'n.', 'voiture', 2);
insert into entry (word, pos, definition, dictionary_id) values ('dog', 'n.', 'chien', 2);
insert into entry (word, pos, definition, dictionary_id) values ('egg', 'n.', 'œuf', 2);
insert into entry (word, pos, definition, dictionary_id) values ('fish', 'n.', 'poisson', 2);
insert into entry (word, pos, definition, dictionary_id) values ('grape', 'n.', 'raisin', 2);
insert into entry (word, pos, definition, dictionary_id) values ('house', 'n.', 'maison', 2);
insert into entry (word, pos, definition, dictionary_id) values ('ice', 'n.', 'glace', 2);
insert into entry (word, pos, definition, dictionary_id) values ('juice', 'n.', 'jus', 2);
insert into entry (word, pos, definition, dictionary_id) values ('key', 'n.', 'clé', 2);
insert into entry (word, pos, definition, dictionary_id) values ('lemon', 'n.', 'citron', 2);
insert into entry (word, pos, definition, dictionary_id) values ('milk', 'n.', 'lait', 2);
insert into entry (word, pos, definition, dictionary_id) values ('night', 'n.', 'nuit', 2);
insert into entry (word, pos, definition, dictionary_id) values ('orange', 'n.', 'orange', 2);
insert into entry (word, pos, definition, dictionary_id) values ('pen', 'n.', 'stylo', 2);
insert into entry (word, pos, definition, dictionary_id) values ('cat', 'n.', 'chat', 2);
insert into entry (word, pos, definition, dictionary_id) values ('bread', 'n.', 'pain', 2);
insert into entry (word, pos, definition, dictionary_id) values ('water', 'n.', 'eau', 2);
insert into entry (word, pos, definition, dictionary_id) values ('cheese', 'n.', 'fromage', 2);
insert into entry (word, pos, definition, dictionary_id) values ('chair', 'n.', 'chaise', 2);
insert into entry (word, pos, definition, dictionary_id) values ('table', 'n.', 'table', 2);
insert into entry (word, pos, definition, dictionary_id) values ('window', 'n.', 'fenêtre', 2);
insert into entry (word, pos, definition, dictionary_id) values ('door', 'n.', 'porte', 2);
insert into entry (word, pos, definition, dictionary_id) values ('school', 'n.', 'école', 2);
insert into entry (word, pos, definition, dictionary_id) values ('teacher', 'n.', 'professeur', 2);
insert into entry (word, pos, definition, dictionary_id) values ('student', 'n.', 'étudiant', 2);
insert into entry (word, pos, definition, dictionary_id) values ('computer', 'n.', 'ordinateur', 2);
insert into entry (word, pos, definition, dictionary_id) values ('phone', 'n.', 'téléphone', 2);
insert into entry (word, pos, definition, dictionary_id) values ('mouse', 'n.', 'souris', 2);
insert into entry (word, pos, definition, dictionary_id) values ('keyboard', 'n.', 'clavier', 2);
insert into entry (word, pos, definition, dictionary_id) values ('monitor', 'n.', 'moniteur', 2);
insert into entry (word, pos, definition, dictionary_id) values ('printer', 'n.', 'imprimante', 2);
insert into entry (word, pos, definition, dictionary_id) values ('notebook', 'n.', 'cahier', 2);
insert into entry (word, pos, definition, dictionary_id) values ('pencil', 'n.', 'crayon', 2);
insert into entry (word, pos, definition, dictionary_id) values ('eraser', 'n.', 'gomme', 2);
insert into entry (word, pos, definition, dictionary_id) values ('sharpener', 'n.', 'taille-crayon', 2);
insert into entry (word, pos, definition, dictionary_id) values ('backpack', 'n.', 'sac à dos', 2);
insert into entry (word, pos, definition, dictionary_id) values ('paper', 'n.', 'papier', 2);
insert into entry (word, pos, definition, dictionary_id) values ('magazine', 'n.', 'magazine', 2);
insert into entry (word, pos, definition, dictionary_id) values ('newspaper', 'n.', 'journal', 2);
insert into entry (word, pos, definition, dictionary_id) values ('letter', 'n.', 'lettre', 2);
insert into entry (word, pos, definition, dictionary_id) values ('envelope', 'n.', 'enveloppe', 2);
insert into entry (word, pos, definition, dictionary_id) values ('stamp', 'n.', 'timbre', 2);
insert into entry (word, pos, definition, dictionary_id) values ('package', 'n.', 'colis', 2);
insert into entry (word, pos, definition, dictionary_id) values ('postcard', 'n.', 'carte postale', 2);
insert into entry (word, pos, definition, dictionary_id) values ('clock', 'n.', 'horloge', 2);
insert into entry (word, pos, definition, dictionary_id) values ('watch', 'n.', 'montre', 2);
insert into entry (word, pos, definition, dictionary_id) values ('calendar', 'n.', 'calendrier', 2);
insert into entry (word, pos, definition, dictionary_id) values ('alarm', 'n.', 'alarme', 2);
insert into entry (word, pos, definition, dictionary_id) values ('bed', 'n.', 'lit', 2);
insert into entry (word, pos, definition, dictionary_id) values ('pillow', 'n.', 'oreiller', 2);
insert into entry (word, pos, definition, dictionary_id) values ('blanket', 'n.', 'couverture', 2);
insert into entry (word, pos, definition, dictionary_id) values ('sheet', 'n.', 'drap', 2);
insert into entry (word, pos, definition, dictionary_id) values ('closet', 'n.', 'placard', 2);
insert into entry (word, pos, definition, dictionary_id) values ('drawer', 'n.', 'tiroir', 2);
insert into entry (word, pos, definition, dictionary_id) values ('lamp', 'n.', 'lampe', 2);
insert into entry (word, pos, definition, dictionary_id) values ('fan', 'n.', 'ventilateur', 2);
insert into entry (word, pos, definition, dictionary_id) values ('heater', 'n.', 'chauffage', 2);
insert into entry (word, pos, definition, dictionary_id) values ('air conditioner', 'n.', 'climatiseur', 2);
insert into entry (word, pos, definition, dictionary_id) values ('vacuum', 'n.', 'aspirateur', 2);
insert into entry (word, pos, definition, dictionary_id) values ('broom', 'n.', 'balai', 2);
insert into entry (word, pos, definition, dictionary_id) values ('mop', 'n.', 'serpillière', 2);
insert into entry (word, pos, definition, dictionary_id) values ('bucket', 'n.', 'seau', 2);
insert into entry (word, pos, definition, dictionary_id) values ('soap', 'n.', 'savon', 2);
insert into entry (word, pos, definition, dictionary_id) values ('shampoo', 'n.', 'shampoing', 2);
insert into entry (word, pos, definition, dictionary_id) values ('toothbrush', 'n.', 'brosse à dents', 2);
insert into entry (word, pos, definition, dictionary_id) values ('toothpaste', 'n.', 'dentifrice', 2);
insert into entry (word, pos, definition, dictionary_id) values ('towel', 'n.', 'serviette', 2);
insert into entry (word, pos, definition, dictionary_id) values ('shower', 'n.', 'douche', 2);
insert into entry (word, pos, definition, dictionary_id) values ('bath', 'n.', 'bain', 2);
insert into entry (word, pos, definition, dictionary_id) values ('mirror', 'n.', 'miroir', 2);
insert into entry (word, pos, definition, dictionary_id) values ('sink', 'n.', 'évier', 2);


insert into entry (word, pos, definition, dictionary_id) values ('apple', 'n.', 'manzana', 3);
insert into entry (word, pos, definition, dictionary_id) values ('book', 'n.', 'libro', 3);
insert into entry (word, pos, definition, dictionary_id) values ('car', 'n.', 'coche', 3);
insert into entry (word, pos, definition, dictionary_id) values ('dog', 'n.', 'perro', 3);
insert into entry (word, pos, definition, dictionary_id) values ('egg', 'n.', 'huevo', 3);
insert into entry (word, pos, definition, dictionary_id) values ('fish', 'n.', 'pez', 3);
insert into entry (word, pos, definition, dictionary_id) values ('grape', 'n.', 'uva', 3);
insert into entry (word, pos, definition, dictionary_id) values ('house', 'n.', 'casa', 3);
insert into entry (word, pos, definition, dictionary_id) values ('ice', 'n.', 'hielo', 3);
insert into entry (word, pos, definition, dictionary_id) values ('juice', 'n.', 'jugo', 3);
insert into entry (word, pos, definition, dictionary_id) values ('key', 'n.', 'llave', 3);
insert into entry (word, pos, definition, dictionary_id) values ('lemon', 'n.', 'limón', 3);
insert into entry (word, pos, definition, dictionary_id) values ('milk', 'n.', 'leche', 3);
insert into entry (word, pos, definition, dictionary_id) values ('night', 'n.', 'noche', 3);
insert into entry (word, pos, definition, dictionary_id) values ('orange', 'n.', 'naranja', 3);
insert into entry (word, pos, definition, dictionary_id) values ('pen', 'n.', 'bolígrafo', 3);
insert into entry (word, pos, definition, dictionary_id) values ('cat', 'n.', 'gato', 3);
insert into entry (word, pos, definition, dictionary_id) values ('bread', 'n.', 'pan', 3);
insert into entry (word, pos, definition, dictionary_id) values ('water', 'n.', 'agua', 3);
insert into entry (word, pos, definition, dictionary_id) values ('cheese', 'n.', 'queso', 3);
insert into entry (word, pos, definition, dictionary_id) values ('chair', 'n.', 'silla', 3);
insert into entry (word, pos, definition, dictionary_id) values ('table', 'n.', 'mesa', 3);
insert into entry (word, pos, definition, dictionary_id) values ('window', 'n.', 'ventana', 3);
insert into entry (word, pos, definition, dictionary_id) values ('door', 'n.', 'puerta', 3);
insert into entry (word, pos, definition, dictionary_id) values ('school', 'n.', 'escuela', 3);
insert into entry (word, pos, definition, dictionary_id) values ('teacher', 'n.', 'profesor', 3);
insert into entry (word, pos, definition, dictionary_id) values ('student', 'n.', 'estudiante', 3);
insert into entry (word, pos, definition, dictionary_id) values ('computer', 'n.', 'computadora', 3);
insert into entry (word, pos, definition, dictionary_id) values ('phone', 'n.', 'teléfono', 3);
insert into entry (word, pos, definition, dictionary_id) values ('mouse', 'n.', 'ratón', 3);
insert into entry (word, pos, definition, dictionary_id) values ('keyboard', 'n.', 'teclado', 3);
insert into entry (word, pos, definition, dictionary_id) values ('monitor', 'n.', 'monitor', 3);
insert into entry (word, pos, definition, dictionary_id) values ('printer', 'n.', 'impresora', 3);
insert into entry (word, pos, definition, dictionary_id) values ('notebook', 'n.', 'cuaderno', 3);
insert into entry (word, pos, definition, dictionary_id) values ('pencil', 'n.', 'lápiz', 3);
insert into entry (word, pos, definition, dictionary_id) values ('eraser', 'n.', 'borrador', 3);
insert into entry (word, pos, definition, dictionary_id) values ('sharpener', 'n.', 'sacapuntas', 3);
insert into entry (word, pos, definition, dictionary_id) values ('backpack', 'n.', 'mochila', 3);
insert into entry (word, pos, definition, dictionary_id) values ('paper', 'n.', 'papel', 3);
insert into entry (word, pos, definition, dictionary_id) values ('magazine', 'n.', 'revista', 3);
insert into entry (word, pos, definition, dictionary_id) values ('newspaper', 'n.', 'periódico', 3);
insert into entry (word, pos, definition, dictionary_id) values ('letter', 'n.', 'carta', 3);
insert into entry (word, pos, definition, dictionary_id) values ('envelope', 'n.', 'sobre', 3);
insert into entry (word, pos, definition, dictionary_id) values ('stamp', 'n.', 'sello', 3);
insert into entry (word, pos, definition, dictionary_id) values ('package', 'n.', 'paquete', 3);
insert into entry (word, pos, definition, dictionary_id) values ('postcard', 'n.', 'tarjeta postal', 3);
insert into entry (word, pos, definition, dictionary_id) values ('clock', 'n.', 'reloj', 3);
insert into entry (word, pos, definition, dictionary_id) values ('watch', 'n.', 'reloj', 3);
insert into entry (word, pos, definition, dictionary_id) values ('calendar', 'n.', 'calendario', 3);
insert into entry (word, pos, definition, dictionary_id) values ('alarm', 'n.', 'alarma', 3);
insert into entry (word, pos, definition, dictionary_id) values ('bed', 'n.', 'cama', 3);
insert into entry (word, pos, definition, dictionary_id) values ('pillow', 'n.', 'almohada', 3);
insert into entry (word, pos, definition, dictionary_id) values ('blanket', 'n.', 'manta', 3);
insert into entry (word, pos, definition, dictionary_id) values ('sheet', 'n.', 'sábana', 3);
insert into entry (word, pos, definition, dictionary_id) values ('closet', 'n.', 'armario', 3);
insert into entry (word, pos, definition, dictionary_id) values ('drawer', 'n.', 'cajón', 3);
insert into entry (word, pos, definition, dictionary_id) values ('lamp', 'n.', 'lámpara', 3);
insert into entry (word, pos, definition, dictionary_id) values ('fan', 'n.', 'ventilador', 3);
insert into entry (word, pos, definition, dictionary_id) values ('heater', 'n.', 'calefactor', 3);
insert into entry (word, pos, definition, dictionary_id) values ('air conditioner', 'n.', 'aire acondicionado', 3);
insert into entry (word, pos, definition, dictionary_id) values ('vacuum', 'n.', 'aspiradora', 3);
insert into entry (word, pos, definition, dictionary_id) values ('broom', 'n.', 'escoba', 3);
insert into entry (word, pos, definition, dictionary_id) values ('mop', 'n.', 'fregona', 3);
insert into entry (word, pos, definition, dictionary_id) values ('bucket', 'n.', 'cubeta', 3);
insert into entry (word, pos, definition, dictionary_id) values ('soap', 'n.', 'jabón', 3);
insert into entry (word, pos, definition, dictionary_id) values ('shampoo', 'n.', 'champú', 3);
insert into entry (word, pos, definition, dictionary_id) values ('toothbrush', 'n.', 'cepillo de dientes', 3);
insert into entry (word, pos, definition, dictionary_id) values ('toothpaste', 'n.', 'pasta de dientes', 3);
insert into entry (word, pos, definition, dictionary_id) values ('towel', 'n.', 'toalla', 3);
insert into entry (word, pos, definition, dictionary_id) values ('shower', 'n.', 'ducha', 3);
insert into entry (word, pos, definition, dictionary_id) values ('bath', 'n.', 'baño', 3);
insert into entry (word, pos, definition, dictionary_id) values ('mirror', 'n.', 'espejo', 3);
insert into entry (word, pos, definition, dictionary_id) values ('sink', 'n.', 'fregadero', 3);

insert into entry (word, pos, definition, dictionary_id) values ('Ace', 'n.', 'A hole-in-one; when the disc lands in the basket on the first throw.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Albatross', 'n.', 'Completing a hole three strokes under par.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Anhyzer', 'n.', 'A throw where the disc is released with an angle causing it to turn opposite of the natural flight path.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Approach', 'n.', 'A throw intended to land the disc near the basket.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Backhand', 'n.', 'A throw where the disc is released from across the body with the back of the hand facing the target.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Birdie', 'n.', 'Completing a hole one stroke under par.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Bogey', 'n.', 'Completing a hole one stroke over par.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Card', 'n.', 'The group of players competing together in a round.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Chain', 'n.', 'The metal chains in the basket that help catch the disc.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Circle 1', 'n.', 'The area within 10 meters (about 33 feet) of the basket.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Circle 2', 'n.', 'The area between 10 and 20 meters (about 33 to 66 feet) from the basket.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Driver', 'n.', 'A type of disc designed for maximum distance.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Eagle', 'n.', 'Completing a hole two strokes under par.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Fade', 'n.', 'The tendency of a disc to hook left (for right-handed backhand throwers) at the end of its flight.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Fairway', 'n.', 'The in-bounds path leading to the basket.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Forehand', 'n.', 'A throw where the disc is released from the side of the body with the palm facing the target.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Griplock', 'n.', 'When the disc is released too late, often resulting in an undesired throw direction.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Hyzer', 'n.', 'A throw where the disc is released with an angle causing it to follow its natural flight path.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Lie', 'n.', 'The spot where the previous throw landed, from which the next throw is made.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Midrange', 'n.', 'A type of disc designed for control and accuracy over distance.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('OB (Out of Bounds)', 'n.', 'Areas designated as out-of-play, resulting in a penalty stroke if the disc lands there.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Overstable', 'n.', 'A disc that has a strong tendency to fade left (for right-handed backhand throwers).', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Par', 'n.', 'The number of throws expected to complete the hole.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Putter', 'n.', 'A type of disc designed for short, controlled throws into the basket.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Roller', 'n.', 'A throw where the disc is intended to land on its edge and roll.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('S-curve', 'n.', 'A throw where the disc turns in one direction before fading back in the other direction.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Stable', 'n.', 'A disc that flies straight with minimal turn or fade.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Tee Pad', 'n.', 'The designated area where the first throw of each hole is made.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Turn', 'n.', 'The tendency of a disc to curve right (for right-handed backhand throwers) early in its flight.', 4);
insert into entry (word, pos, definition, dictionary_id) values ('Understable', 'n.', 'A disc that has a strong tendency to turn right (for right-handed backhand throwers).', 4);

insert into entry (word, pos, definition, dictionary_id) values ('Annual', 'n.', 'A plant that completes its life cycle in one growing season.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Biennial', 'n.', 'A plant that completes its life cycle in two growing seasons.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Compost', 'n.', 'Decomposed organic matter used to improve soil structure and provide nutrients.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Cultivate', 'v.', 'To prepare and work on (soil) to promote the growth of plants.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Fertilizer', 'n.', 'A substance added to soil to enhance the growth of plants.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Germinate', 'v.', 'To begin to grow or sprout from a seed.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Herbaceous', 'adj.', 'Plants with non-woody stems that die back at the end of the growing season.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Hydroponics', 'n.', 'A method of growing plants without soil, using nutrient-rich water.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Irrigation', 'n.', 'The artificial application of water to soil to assist in growing crops.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Mulch', 'n.', 'A material spread over soil to retain moisture, suppress weeds, and regulate temperature.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Perennial', 'n.', 'A plant that lives for more than two years.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Photosynthesis', 'n.', 'The process by which green plants use sunlight to synthesize foods from carbon dioxide and water.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Pruning', 'v.', 'The selective removal of certain parts of a plant, such as branches, buds, or roots.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Rhizome', 'n.', 'A continuously growing horizontal underground stem that puts out lateral shoots and adventitious roots at intervals.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Seedling', 'n.', 'A young plant, especially one raised from seed and not from a cutting.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Sow', 'v.', 'To plant seeds in the ground for growth.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Thinning', 'v.', 'The process of removing excess plants to allow remaining plants more space to grow.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Transplant', 'v.', 'To move a plant from one location to another.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Trowel', 'n.', 'A small handheld tool with a curved scoop for lifting plants or earth.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Vermiculture', 'n.', 'The use of worms to decompose organic food waste, turning it into nutrient-rich material for plants.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Weed', 'n.', 'A wild plant growing where it is not wanted and in competition with cultivated plants.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Composting', 'v.', 'The process of recycling organic matter, such as leaves and food scraps, into fertilizer.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Deadheading', 'v.', 'The removal of dead flowers from a plant to encourage further blooming.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Foliar', 'adj.', 'Relating to or having to do with leaves.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Grafting', 'v.', 'The process of joining two plants together so that they grow as one.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Hardening off', 'v.', 'The process of gradually acclimatizing indoor or greenhouse plants to outdoor conditions.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Heirloom', 'adj.', 'A traditional variety of plant that has been passed down through generations.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Horticulture', 'n.', 'The art or practice of garden cultivation and management.', 5);
insert into entry (word, pos, definition, dictionary_id) values ('Humus', 'n.', 'Rich, dark organic material formed by the decay of vegetable matter, essential to soil fertility.', 5);



COMMIT TRANSACTION;
